import { Component } from '@angular/core';
import { QA } from './faq.interface';
import { QaItem } from './qa-item/qa-item';

@Component({
  selector: 'app-faq',
  imports: [QaItem],
  templateUrl: './faq.html',
  styleUrl: './faq.scss',
})
export class Faq {
  qa: QA[] = [
    {
      question: 'How does the AI resume generator work?',
      answer:
        'It uses the details you enter to draft resume sections like summaries, experience bullets, and education notes. The AI is instructed to stick to your inputs and not invent details.',
    },
    {
      question: 'Can I edit my AI-generated resume?',
      answer:
        'Yes! Every resume generated by ResumeCrafts AI is fully editable, allowing you to tweak content, style, and formatting to match your personal preferences.',
    },
    {
      question: 'Does ResumeCrafts AI help with cover letters?',
      answer:
        'Yes. You can generate a cover letter by providing a job description, company name, position, and your preferred tone.',
    },
    {
      question: 'Is there a free plan?',
      answer:
        'Yes. The Free plan includes the resume builder, templates, job tracker, limited AI generations per month, and PDF export.',
    },
  ];
}
