import { Component } from '@angular/core';
import { QA } from './faq.interface';
import { QaItem } from './qa-item/qa-item';

@Component({
  selector: 'app-faq',
  imports: [QaItem],
  templateUrl: './faq.html',
  styleUrl: './faq.scss',
})
export class Faq {
  qa: QA[] = [
    {
      question: 'How does the AI resume generator work?',
      answer:
        'AI analyzes your experience and the job description to create tailored, ATS-friendly resumes that highlight your strengths.',
    },
    {
      question: 'Can I edit my AI-generated resume?',
      answer:
        'Yes! Every resume generated by CareerForge AI is fully editable, allowing you to tweak content, style, and formatting to match your personal preferences.',
    },
    {
      question: 'Does CareerForge AI help with LinkedIn optimization?',
      answer:
        'Absolutely! The platform provides personalized tips for improving your LinkedIn profile, including headlines, summaries, and keyword recommendations to attract recruiters.',
    },
    {
      question: 'Can I try CareerForge AI for free?',
      answer:
        'Yes! You can sign up for a free plan to test the AI resume generator and LinkedIn optimization features before upgrading to a paid subscription.',
    },
  ];
}
